# Generated by Django 4.2.4 on 2023-09-05 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('address', models.TextField(verbose_name='indirizzo')),
                ('fiscal_code', models.CharField(max_length=16, unique=True, verbose_name='codice fiscale')),
                ('vat_number', models.CharField(max_length=16, unique=True, verbose_name='P.IVA')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clienti',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True, verbose_name='numero fattura')),
                ('issuance_date', models.DateField(verbose_name='data di emissione')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='importo totale')),
                ('invoice_signed_in_cades', models.BooleanField(blank=True, default=False, help_text='spunta se firmato', verbose_name='Firmato')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.client')),
            ],
            options={
                'verbose_name': 'fattura',
                'verbose_name_plural': 'fatture',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('description', models.TextField(verbose_name='descrizione')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prezzo')),
                ('quantity_in_stock', models.PositiveIntegerField(default=0, verbose_name='quantità in magazzino')),
            ],
            options={
                'verbose_name': 'prodotto',
                'verbose_name_plural': 'prodotti',
            },
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, null=True, verbose_name='quantità')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_details', to='master_data.invoice', verbose_name='fattura')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.product', verbose_name='prodotto')),
            ],
            options={
                'verbose_name': 'dettaglio fattura',
                'verbose_name_plural': 'dettaglio fatture',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='products',
            field=models.ManyToManyField(through='master_data.InvoiceDetail', to='master_data.product'),
        ),
    ]
